version: 0.2

env:
  variables:
    ENV: ENV
    REGION: ap-northeast-1
    ACCOUNT: 559300055890
    SERVICE_NAME: ${ENV}-garland
    TASK_FAMILY: ${SERVICE_NAME}
    CONTAINER_NAME: ${SERVICE_NAME}
    ECR_IMAGE_URL: ECR_IMAGE_URL
    LOG_GROUP: LOG_GROUP
    TABLE_NAME: TABLE_NAME
    ACCESS_KEY_ID_ARN: ACCESS_KEY_ID_ARN
    SECRET_ACCESS_KEY_ARN: SECRET_ACCESS_KEY_ARN

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com
  build:
    commands:
      - docker build --platform linux/amd64 -t ${SERVICE_NAME} .
      - docker tag ${SERVICE_NAME}:latest ${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${SERVICE_NAME}:latest
      - docker push ${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${SERVICE_NAME}:latest
  post_build:
    commands:
      - envsubst < taskdef_template.json > taskdef.json
      - envsubst < appspec_template.yml > appspec.yml

artifacts:
  files:
    - taskdef.json
    - appspec.yml
